<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcVBsZr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcVBsZr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcVBsZr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcVBsZr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXcVBsZr\App_KernelDevDebugContainer([
    'container.build_hash' => 'XcVBsZr',
    'container.build_id' => '77c702fe',
    'container.build_time' => 1771868924,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcVBsZr');
