<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2pLJJx9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2pLJJx9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2pLJJx9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2pLJJx9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2pLJJx9\App_KernelDevDebugContainer([
    'container.build_hash' => '2pLJJx9',
    'container.build_id' => '25c192c9',
    'container.build_time' => 1771868913,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2pLJJx9');
