<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfchrEC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfchrEC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfchrEC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfchrEC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVfchrEC\App_KernelDevDebugContainer([
    'container.build_hash' => 'VfchrEC',
    'container.build_id' => '563543ee',
    'container.build_time' => 1771868159,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfchrEC');
